apiVersion: v1
kind: Service
metadata:
  labels:
    app: default-http-backend
    my-ingress: "true"
  name: default-http-backend
  namespace: kube-system
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: default-http-backend
  sessionAffinity: None
  type: NodePort
