apiVersion: v1
data:
  map-hash-bucket-size: "128"
kind: ConfigMap
metadata:
  labels:
    my-ingress: "true"
  name: nginx-load-balancer-conf
  namespace: kube-system
  selfLink: /api/v1/namespaces/kube-system/configmaps/nginx-load-balancer-conf
